### ISSUE TITLE
Add a comment instead of updating PR description

### ISSUE THREAD

**Issue by sureyeaah** [flowwer-dev/pull-request-stats#14]
Hi,

I want the stats to be posted in a new comment instead of being appended to the PR description. Is this possible?

Thanks!

**Comment by manuelmhtr** [comment]
Hi @sureyeaah this was the behavior in version 1, but it was a little annoying because every new push created a new comment with the stats.
I'd like to understand, is the current behavior affecting somehow your project or is just a personal preference?

**Comment by rowi1de** [comment]
@manuelmhtr If you open a PR, edit the description and the Actions runs in the meantime it will cause concurrent edits.
Comment would work if the workflow trigger is set correctly
