### ISSUE TITLE
Feature request: Number of lines reviewed

### ISSUE THREAD

**Issue by BadenMorgan** [flowwer-dev/pull-request-stats#23]
As a developer I would like to know how many lines someone has reviewed so I can more accurately assess if they should be chosen for the next review.

What we have found is sometimes people get more complex reviews than others and I know grading code complexity may be subjective but at a base level maybe just seeing how many lines were reviewed by a user in a given time period could help make the decision easier. 

I got the idea from this repo:
https://github.com/coverwallet/pr-labeler

**Comment by manuelmhtr** [comment]
Hi @BadenMorgan is a good idea. I'll put it together with https://github.com/flowwer-dev/pull-request-stats/pull/17 and make stats columns more configurable.

I'll find some time during the next weeks to make this change.

**Comment by BadenMorgan** [comment]
That's awesome, let me know if you want me to test it out when you are ready, would be happy to help on that front

**Comment by manuelmhtr** [comment]
Working on a web version that allows teams to configure the stats.

**Comment by manuelmhtr** [comment]
Hello @BadenMorgan now this is possible with version [v3](https://github.com/flowwer-dev/pull-request-stats/releases/tag/v3.0.0). There are 6 new metrics:

* `reviewedAdditions`: The total number of added lines reviewed. 
* `reviewedDeletions`: The total number of deleted lines reviewed.
* `reviewedLines`: The total number of lines reviewed (additions + deletions).
* `additions`: The total number of added lines across the opened pull requests.
* `deletions`: The total number of deleted lines across the opened pull requests.
* `lines`: The total number of lines changed (added and deleted) across all pull requests opened by the user.
