### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by ellimist** [flowwer-dev/pull-request-stats#26]
Hi,

Thanks a lot for this project, it seems very useful 🙏🏼 

I'd like to use this internally in some of our projects and willing to send upstream any improvement we'd make, but the current license of the project is pretty prohibitive and I don't think it could fly by our legal department. 

Would you be able to license it to something more permissive, that wouldn't require us to open source _all_ of our source code if we use it?

Thanks a lot,
Adrian

**Comment by manuelmhtr** [comment]
Hi @ellimist,
Thanks for pointing the issue and sorry for the late reply. Truth is, I'm really bad with licenses. Please let me deep into it and come with a better one.

**Comment by manuelmhtr** [comment]
@ellimist I dove into, and definitively AGPLv3 is not what I was looking for when I created this library. Moved to MIT in favor of the community.

I hope this is a good fit for your company.

**Comment by ellimist** [comment]
@manuelmhtr this is amazing, thanks a lot 🙏🏼 I'll try to send back here any changes/improvements we might make on the way.
