### ISSUE TITLE
expandable table to avoid space

### ISSUE THREAD

**Issue by hidayt-rahman-qatalog** [flowwer-dev/pull-request-stats#27]
Do we have any possibility to make it expandable so it won't take space on load but can be viewed by clicking on icon?

<details>
  <summary>Pull reviewers stats</summary>
 
  ## Pull reviewers stats
### Table here
  
  </details>

**Comment by manuelmhtr** [comment]
Hi @hidayt-rahman-qatalog thanks for your suggestion.

I liked this format a lot. I'll work on a version where the table is expanded by default and include and option to start collapsed.

**Comment by manuelmhtr** [comment]
Hi @hidayt-rahman-qatalog I took a different approach. Instead of making it collapsable, now in [v2.4.0](https://github.com/flowwer-dev/pull-request-stats/releases/tag/v2.4.0) the stats are published as a comment. This way it takes no space from description.

**Comment by hidayt-rahman-qatalog** [comment]
Thanks @manuelmhtr, I will try and see if its feasible for us or not.
