### ISSUE TITLE
Request to get verified in the github marketplace

### ISSUE THREAD

**Issue by cmathews88** [flowwer-dev/pull-request-stats#28]
Unable to use this action within my organization because the creator is not Verified.

**Comment by manuelmhtr** [comment]
Hi @cmathews88 
Unfortunately is impossible for me request a verification. I looks Github is currently verifying actions from [closed partners](https://github.community/t/how-to-become-verified-creator-of-a-github-action/116009).

However, you can allow specific action from the [organization settings](https://docs.github.com/en/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization), you can ask an admin to do it.
