### ISSUE TITLE
Feature: options to filter included PRs

### ISSUE THREAD

**Issue by fudomunro** [flowwer-dev/pull-request-stats#31]
We're looking to publish review statistics for PRs that match a certain branch prefix (a convention we use for identifying the originating team). I imagine there are many other ways folk would find it convenient to filter, such as by PR creator, labels, or name.

**Comment by giacomocerquone** [comment]
I'd implement the possibility to provide a whitelist OR blacklist where both can accept regex and/or other kind of filters

**Comment by manuelmhtr** [comment]
Hello @fudomunro @giacomocerquone there's a new filter `exclude` that accepts either a regexp or a list of usernames to be ignored from the stats. I know it's not the exact filter you need but it's a step forward.

**Comment by manuelmhtr** [comment]
There's also a new option `include` in [v3.2.0] to specify the only usernames to be included in the results.
