### ISSUE TITLE
KeyTooLongError: Your key is too long

### ISSUE THREAD

**Issue by http-teapot** [flowwer-dev/pull-request-stats#33]
Looks like I am a heavy reviewer and hit some limits.

```xml
<Error>
  <Code>KeyTooLongError</Code>
  <Message>Your key is too long</Message>
  <Size>1688</Size>
  <MaxSizeAllowed>1024</MaxSizeAllowed>
  <RequestId>CAX6Y7AQ43KMB32Q</RequestId>
  <HostId>w6oonWMFgj6zKXRdwnmiZ3vqpze1chULv4WrcL2evonhQg1Mwwnchb9MumZSxykn69N3l3Ds2tw=</HostId>
</Error>
```

I think the URL is safe to share: [`https://app.flowwer.dev/charts/review-time/~(u~(i~'1534519~n~'http-teapot)~p~30~r~(~(d~'rbu7ub~t~'r4)~(d~'rc319p~t~'fr)~(d~'rbshn6~t~'eqn)~(d~'rbu4wz~t~'58)~(d~'rbu5ok~t~'4jt)~(d~'rbu214~t~'279)~(d~'rbuoke~t~'5m)~(d~'rbuol5~t~'6d)~(d~'rbuovz~t~'40)~(d~'rbuow6~t~'47)~(d~'rbxlmt~t~'8l)~(d~'rc3lyq~t~'b4)~(d~'rc3sqi~t~'1tm)~(d~'rc0ak3~t~'w2w)~(d~'rc0alk~t~'wgx)~(d~'rcjw4o~t~'s0)~(d~'rcgwc8~t~'a4q)~(d~'rcgowx~t~'co)~(d~'rcgpal~t~'qc)~(d~'rcg4ga~t~'8nby)~(d~'rcg47n~t~'36n5)~(d~'rcg4d1~t~'3u7u)~(d~'rcg3xx~t~'guu)~(d~'rc217m~t~'sgv)~(d~'rcgay3~t~'5v5)~(d~'rcgb08~t~'5xa)~(d~'rcgb1s~t~'5yu)~(d~'rcg4lc~t~'8rn7)~(d~'rcg718~t~'1rn)~(d~'rcg72s~t~'1t7)~(d~'rcgbgn~t~'x9)~(d~'rcg3zi~t~'1y5p)~(d~'rcg3ye~t~'1iza)~(d~'rci4rp~t~'1o6j)~(d~'rc59zw~t~'45m6)~(d~'rc6z9s~t~'18q)~(d~'rc7029~t~'4i)~(d~'rc57if~t~'1eac)~(d~'rcci15~t~'3q8)~(d~'rc597x~t~'25q4)~(d~'rc59yy~t~'26h5)~(d~'rccq31~t~'5yxt)~(d~'rck0jt~t~'ak)~(d~'rcik74~t~'4mq)~(d~'rciky8~t~'1uvu)~(d~'rcil02~t~'1xpr)~(d~'rct475~t~'apaq)~(d~'rcg54h~t~'li)~(d~'rct44r~t~'crxy)~(d~'rcikja~t~'7bx)~(d~'rcikqy~t~'7jl)~(d~'rct790~t~'5nl)~(d~'rcuvjm~t~'5dr)~(d~'rcg44n~t~'35jj)~(d~'rct3zy~t~'ctu6)~(d~'rct40m~t~'ctuu)~(d~'rcuvhh~t~'5se)~(d~'rcwq8c~t~'i8j)~(d~'rcwrj2~t~'jj9)~(d~'rcikfc~t~'9nr)~(d~'rcx0k1~t~'er)~(d~'rcuw1o~t~'dsw)~(d~'rct5y9~t~'9jm)~(d~'rcuvtp~t~'7dw)~(d~'rct672~t~'7wh)~(d~'rcuvv3~t~'1xki)~(d~'rcuvx6~t~'759)~(d~'rct62h~t~'15l)~(d~'rcteji~t~'9mm)~(d~'rct6by~t~'7jy)~(d~'rcteju~t~'fru)~(d~'rcg6kw~t~'9ml5)~(d~'rctej0~t~'9vf8)~(d~'rct7bb~t~'1z2f)~(d~'rctmdm~t~'1wn)~(d~'rctlje~t~'46)~(d~'rctacp~t~'236v)~(d~'rd2e9p~t~'cjw)~(d~'rd2ajo~t~'5xfs)~(d~'rd2ane~t~'5xji)~(d~'rcx07d~t~'hmm)~(d~'rd4dai~t~'2gw9)~(d~'rctngl~t~'c6su)~(d~'rd2slg~t~'5dvc)~(d~'rcg6b9~t~'9fzr)))`](https://app.flowwer.dev/charts/review-time/~(u~(i~'1534519~n~'http-teapot)~p~30~r~(~(d~'rbu7ub~t~'r4)~(d~'rc319p~t~'fr)~(d~'rbshn6~t~'eqn)~(d~'rbu4wz~t~'58)~(d~'rbu5ok~t~'4jt)~(d~'rbu214~t~'279)~(d~'rbuoke~t~'5m)~(d~'rbuol5~t~'6d)~(d~'rbuovz~t~'40)~(d~'rbuow6~t~'47)~(d~'rbxlmt~t~'8l)~(d~'rc3lyq~t~'b4)~(d~'rc3sqi~t~'1tm)~(d~'rc0ak3~t~'w2w)~(d~'rc0alk~t~'wgx)~(d~'rcjw4o~t~'s0)~(d~'rcgwc8~t~'a4q)~(d~'rcgowx~t~'co)~(d~'rcgpal~t~'qc)~(d~'rcg4ga~t~'8nby)~(d~'rcg47n~t~'36n5)~(d~'rcg4d1~t~'3u7u)~(d~'rcg3xx~t~'guu)~(d~'rc217m~t~'sgv)~(d~'rcgay3~t~'5v5)~(d~'rcgb08~t~'5xa)~(d~'rcgb1s~t~'5yu)~(d~'rcg4lc~t~'8rn7)~(d~'rcg718~t~'1rn)~(d~'rcg72s~t~'1t7)~(d~'rcgbgn~t~'x9)~(d~'rcg3zi~t~'1y5p)~(d~'rcg3ye~t~'1iza)~(d~'rci4rp~t~'1o6j)~(d~'rc59zw~t~'45m6)~(d~'rc6z9s~t~'18q)~(d~'rc7029~t~'4i)~(d~'rc57if~t~'1eac)~(d~'rcci15~t~'3q8)~(d~'rc597x~t~'25q4)~(d~'rc59yy~t~'26h5)~(d~'rccq31~t~'5yxt)~(d~'rck0jt~t~'ak)~(d~'rcik74~t~'4mq)~(d~'rciky8~t~'1uvu)~(d~'rcil02~t~'1xpr)~(d~'rct475~t~'apaq)~(d~'rcg54h~t~'li)~(d~'rct44r~t~'crxy)~(d~'rcikja~t~'7bx)~(d~'rcikqy~t~'7jl)~(d~'rct790~t~'5nl)~(d~'rcuvjm~t~'5dr)~(d~'rcg44n~t~'35jj)~(d~'rct3zy~t~'ctu6)~(d~'rct40m~t~'ctuu)~(d~'rcuvhh~t~'5se)~(d~'rcwq8c~t~'i8j)~(d~'rcwrj2~t~'jj9)~(d~'rcikfc~t~'9nr)~(d~'rcx0k1~t~'er)~(d~'rcuw1o~t~'dsw)~(d~'rct5y9~t~'9jm)~(d~'rcuvtp~t~'7dw)~(d~'rct672~t~'7wh)~(d~'rcuvv3~t~'1xki)~(d~'rcuvx6~t~'759)~(d~'rct62h~t~'15l)~(d~'rcteji~t~'9mm)~(d~'rct6by~t~'7jy)~(d~'rcteju~t~'fru)~(d~'rcg6kw~t~'9ml5)~(d~'rctej0~t~'9vf8)~(d~'rct7bb~t~'1z2f)~(d~'rctmdm~t~'1wn)~(d~'rctlje~t~'46)~(d~'rctacp~t~'236v)~(d~'rd2e9p~t~'cjw)~(d~'rd2ajo~t~'5xfs)~(d~'rd2ane~t~'5xji)~(d~'rcx07d~t~'hmm)~(d~'rd4dai~t~'2gw9)~(d~'rctngl~t~'c6su)~(d~'rd2slg~t~'5dvc)~(d~'rcg6b9~t~'9fzr))))

**Comment by manuelmhtr** [comment]
Hi @http-teapot thanks for reporting the issue. The fix is available in [v2.3.2](https://github.com/flowwer-dev/pull-request-stats/releases/tag/v2.3.2).
It takes the most recent N data points that keeps the URL length below the 1,024 maximum characters.
