### ISSUE TITLE
Error on running the action with `schedule` event

### ISSUE THREAD

**Issue by anshsrtv** [flowwer-dev/pull-request-stats#34]
Getting this error, while running the action on `schedule` event. We're using slack integration and want the stats to be published as a message everyday in a slack channel.
![Screenshot 2022-06-09 at 7 51 24 PM](https://user-images.githubusercontent.com/49693160/172870176-91e0abd8-619f-437b-845a-975c8e102621.png)

**Comment by manuelmhtr** [comment]
Hi @anshsrtv thanks for reporting the issue. The fix is available in [v2.3.2](https://github.com/flowwer-dev/pull-request-stats/releases/tag/v2.3.2), you should be able to run it now.
