### ISSUE TITLE
Feature Request: Can you enable the workflow to be run on demand?

### ISSUE THREAD

**Issue by sivakku** [flowwer-dev/pull-request-stats#4]
Enable it on the trigger "on: workflow_dispatch"

**Comment by manuelmhtr** [comment]
Hi @sivakku unfortunately the action needs a pull request to comment the results on it.
But I like the idea to make it on demand, where would you like to publish the results?

**Comment by runmael** [comment]
Hey @manuelmhtr, could you consider posting results to [Job Summary](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary). This way `workflow_dispatch` could be used. Thanks!

**Comment by manuelmhtr** [comment]
Thanks @runmael!
It's ready on [v2.7.0](https://github.com/flowwer-dev/pull-request-stats/releases/tag/v2.7.0) 🤘
