### ISSUE TITLE
Run nightly and display results in html but not linked to any PR

### ISSUE THREAD

**Issue by valeriupredoi** [flowwer-dev/pull-request-stats#40]
Hey guys, first off - really like this tool, many thanks for putting it together! Second, was wondering if there's a way to run the action nightly (this is possible no problemo) but make it output the stats table in some sort of html file (or even stdout in the GA terminal) so we can create a badge that links to the stats table to be seen at any time by any user, and not be linked to opening/pushing to pull requests. So basically instead of `COMMENT`, get it to output to an html file everytime it runs nightly. Cheers muchly :beer:

**Comment by manuelmhtr** [comment]
Hi @valeriupredoi is a very good idea. Actually, there's a [web versión](https://app.flowwer.dev/charts/review-time/~(u~(i~'2741~n~'ddh)~p~30~r~(~(d~'qq57xy~t~'3co)~(d~'qqedft~t~'i1i)~(d~'qqfmub~t~'1rg0)~(d~'qqhjco~t~'5u)~(d~'qqlxa9~t~'20lw)~(d~'qqqo38~t~'2kp)~(d~'qpgl4i~t~'40i)~(d~'qpgq0r~t~'8wr)~(d~'qpgqv1~t~'9r1)~(d~'qqdzub~t~'398)~(d~'qq2xpc~t~'iz)~(d~'qpgoox~t~'1ep)~(d~'qpggla~t~'dt)~(d~'qpin24~t~'3nk)~(d~'qpi9kk~t~'1a89)~(d~'qpf7la~t~'jlz)~(d~'qprdyz~t~'1201)~(d~'qprf42~t~'1354)~(d~'qq4tod~t~'4ye)~(d~'qq4u7p~t~'5hq)~(d~'qq4wf3~t~'7p4)~(d~'qq4wgp~t~'7qq)~(d~'qq4g4a~t~'2v3)~(d~'qptb3r~t~'25p)~(d~'qpobfp~t~'2aq)~(d~'qq70w7~t~'ux)~(d~'qq6p5h~t~'g3d)~(d~'qqedrz~t~'im6)~(d~'qqg4sc~t~'b4)~(d~'qqlxo9~t~'a4s)~(d~'qqun50~t~'2nz)~(d~'qqr8mt~t~'14q)~(d~'qqumbp~t~'1fp)))) for the app, but is currently used to display the historical stats of each developer.

I can create a new view to display the table and perhaps add some more stats. Do you think it may work?

**Comment by valeriupredoi** [comment]
@manuelmhtr many thanks, mate, and my apologies for the tardy reply! That'd be very nice, do you need any sort of help? I can test and review to the very least, for sure :beer:

**Comment by manuelmhtr** [comment]
Hi! [v2.11.0](https://github.com/flowwer-dev/pull-request-stats/releases/tag/v2.11.0) now outputs results as Markdown and JSON. You can use them along with a [`schedule`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule) trigger to accomplish it.
