### ISSUE TITLE
Feature: Add a Network of Reviewers 

### ISSUE THREAD

**Issue by rowi1de** [flowwer-dev/pull-request-stats#43]
- It would be super helpful to show a network of reviewers
- Who is reviewing (how many) PRs from which Author 
- Stats per Graph Edge 
- ...

**Comment by manuelmhtr** [comment]
Hi @rowi1de that's a great idea, thanks!
It requires considerable effort, so it may take a while to be be ready but I'm definitely doing it 🤘
