### ISSUE TITLE
Sponsorship queries prevents usage in GitHub Enterprise

### ISSUE THREAD

**Issue by erodewald** [flowwer-dev/pull-request-stats#48]
This is likely also the case for any non-GitHub.com hosted instances.

**Error:**
```
Error: Error fetching sponsorships with logins: "["iot"]". Error: GraphqlResponseError: Request failed due to following response errors:
 - Field 'isSponsoredBy' doesn't exist on type 'User'
```

**Runner log:**
```
 ##[debug]Execution failed with error: Error fetching sponsorships with logins: "["iot"]". Error: GraphqlResponseError: Request failed due to following response errors:
##[debug] - Field 'isSponsoredBy' doesn't exist on type 'User'
##[debug]Error: Error fetching sponsorships with logins: "["iot"]". Error: GraphqlResponseError: Request failed due to following response errors:
##[debug] - Field 'isSponsoredBy' doesn't exist on type 'User'
##[debug]    at /runner/_work/_actions/flowwer-dev/pull-request-stats/v2.4.5/dist/index.js:1105:11
##[debug]    at processTicksAndRejections (internal/process/task_queues.js:97:5)
##[debug]    at async module.exports.402.module.exports (/runner/_work/_actions/flowwer-dev/pull-request-stats/v2.4.5/dist/index.js:7042:20)
##[debug]    at async module.exports.662.module.exports (/runner/_work/_actions/flowwer-dev/pull-request-stats/v2.4.5/dist/index.js:13933:21)
##[debug]    at async run (/runner/_work/_actions/flowwer-dev/pull-request-stats/v2.4.5/dist/index.js:14744:5)
```

My understanding is that this action now requires checking sponsorship through the GitHub octokit graphql API, which does not work when running this action in a self-hosted GitHub instance. In my case, this is happening in **GHES 3.5**. When a GitHub runner executes actions, it injects `GITHUB_API_URL` (among other `GITHUB_`-prefixed env variables that define the GH environment). 

I believe Octokit may require additional setup to support custom environments, e.g.,
```javascript
new github.getOctokit(token, { baseUrl: process.env.GITHUB_API_URL });
```

However, this is never going to solve the problem where my `GITHUB_TOKEN` is valid only for the hosted environment, and will be unable to be used for an API request to github.com.

**Do you have guidance?** I'd be happy to just go without the sponsored features but it simply doesn't take non-Github.com environments into consideration.

**Comment by manuelmhtr** [comment]
Hi @erodewald,
Sorry about this problem and thank you for taking the time to include all the details. Honestly I have not worked with the Enterprise version and wasn't aware of this kind of problems.

I think I came with a solution in [v2.4.6](https://github.com/flowwer-dev/pull-request-stats/releases/tag/v2.4.6), it's quite simple: it ignores the error, and assumes no sponsorship.

The only drawback is sponsors on Enterprise environments won't be detected automatically (it wouldn't work anyway), but they can be treated as [external sponsors].

Please give it a try (it's already on `master`) and share with me if that worked.

Thanks,

**Comment by erodewald** [comment]
@manuelmhtr thanks, it works as expected now. 👍 

**Totally unrelated:** use caution with relying on only the `organization` field, without a sensible constraint on `limit`: 
```
Error commenting on the pull request, with variables "{"input":{"body":"## Pull reviewers stats
......
- Body is too long (maximum is 65536 characters)
```
