### ISSUE TITLE
Incorrect use of private vs public repository

### ISSUE THREAD

**Issue by Tucug** [flowwer-dev/pull-request-stats#53]
Hello, 

Thanks for your work. 

We noticed a few issue when using this action with our own instance of GitHub. 

1) The links all point to github.com instead of our instance.
2) If the job is run in a repo marked as public, the analyze over the whole organization will only consider public repositories while a repository marked as private will only look at these one. If this is an expected behavior, maybe documenting it would be nice.
3) The number of PR analyzed is limited. In the log it indicates 1000 PR which is much less than the approximate 100'000 we have. 

Cheers

**Comment by manuelmhtr** [comment]
Currently not supporting private Github instances due to API limitations.
