### ISSUE TITLE
Would you consider creating a locally runnable script out of this action?

### ISSUE THREAD

**Issue by giacomocerquone** [flowwer-dev/pull-request-stats#54]
Hey there, do you think would be easy and useful to provide a locally runnable version of this very same tool instead of the Github actions?

My use case is that I've no permission for example on the repo I work on to add an action but, probably(?), the permissions I have over the repository should allow me to pull the info to produce these stats

**Comment by manuelmhtr** [comment]
Hi @giacomocerquone,
Unfortunately, there's no native way to run it locally, however, you may try using [nektos/act](https://github.com/nektos/act). I haven't tried it, but it may work. Nonetheless, the whole action depends on Github's API, so there's a chance you are missing another permission as well :/

My final recommendation is to ask somebody in your team to install the action, most managers tend to like it.

Hope it helps.

**Comment by giacomocerquone** [comment]
I actually found [monocle](https://github.com/change-metrics/monocle) which is fantastic and does exactly what I was asking!

Thanks by the way @manuelmhtr

**Comment by manuelmhtr** [comment]
I'm glad it worked @giacomocerquone. Happy to help.
