### ISSUE TITLE
Last repository is missing in slack/teams message body

### ISSUE THREAD

**Issue by eodmsabc** [flowwer-dev/pull-request-stats#59]
Repo list in message body is different between comment and slack/teams integration

Suppose that user put `repositories: repo1,repo2,repo3` in workflow parameter, message body shows as follows.
- Comment: `Stats of the last 14 days for repo1, repo2 and repo3`
- Slack: `Stats of the last 14 days for repo1 and repo2`

### Cause
true-source `repos` are being modified during `buildFullList()` function by `pop()`
https://github.com/flowwer-dev/pull-request-stats/blob/b1e65544516bed63e14204d605ac609227f96c96/src/utils/buildSources.js#L25-L31

**Comment by manuelmhtr** [comment]
Thanks you @eodmsabc! Your fix is available now in [v2.6.2](https://github.com/flowwer-dev/pull-request-stats/releases/tag/v2.6.2).
