### ISSUE TITLE
Comments show up when PR made against non-main branches

### ISSUE THREAD

**Issue by macohen** [flowwer-dev/pull-request-stats#62]
I have a bug in my own project here that explains the issue, but I'm hoping you can help: https://github.com/opensearch-project/search-processor/issues/66

**Comment by manuelmhtr** [comment]
Hi @macohen, thanks for reporting the problem.
The action seems to be missing the `write` permission for `pull-requests`. So I [overwrote them](https://github.com/opensearch-project/search-processor/pull/67) to let the action post the results in the pull request. I hope it helps.

I also added this problem in the [Troubleshooting](https://github.com/flowwer-dev/pull-request-stats/edit/master/README.md#troubleshooting) as this may happen to other developers.

Best!
