### ISSUE TITLE
Feature: opened pull requests

### ISSUE THREAD

**Issue by adzuci** [flowwer-dev/pull-request-stats#66]
Hi there!  First off I really love this tool, thank you for all your efforts!

I'm interested in being able to include number of opened pull requests in the output table and believe that data is in the dataset and could be added [here](https://github.com/flowwer-dev/pull-request-stats/blob/master/src/interactors/buildTable/getTableData.js#L69-L89) somehow.

Would that be a reasonable thing to add and if so would it be very difficult?

**Comment by manuelmhtr** [comment]
Hi @adzuci, it's easy to add, but I've received many requests on different stats, so which ones should be added that add the most value?

I'm working on a web version that allows each team to decide which stats to present, I hope it's released soon ;)
