### ISSUE TITLE
If PR stats table is first item in the PR, the "already published" check fails

### ISSUE THREAD

**Issue by derek-young** [flowwer-dev/pull-request-stats#7]
If there is no other content in the PR body, the check in alreadyPublished.js returns false instead of true, and two tables get published to the PR description. I believe this is because the regex is prefixed with a new line character, so if there is not a line above the table, it returns false: `const regexp = new RegExp(`\\n(${TABLE_TITLE})\\n`);`. Unfortunately, I don't have time for a PR now, but wanted to open the issue so it wasn't lost! Thanks Manuel

**Comment by manuelmhtr** [comment]
Ohh great finding! Thanks @derek-young 
No problem, I'll send the fix as soon as possible.

**Comment by manuelmhtr** [comment]
Fixed in [v2.0.3](https://github.com/flowwer-dev/pull-request-stats/releases/tag/v2.0.3)

**Comment by manuelmhtr** [comment]
Hi @derek-young we forgot to build the changes (`yarn build`) LOL.
Now they are published in [v2.1.0](https://github.com/flowwer-dev/pull-request-stats/releases/tag/v2.1.0)

Just in case you still had problems with the action.
