### ISSUE TITLE
Feature: Allow output from action to be consumed in a future step

### ISSUE THREAD

**Issue by damccorm** [flowwer-dev/pull-request-stats#72]
For my specific use case, I'm interested in sending an email with the results to a distribution list (the [apache/beam](https://github.com/apache/beam) developer [email list](https://lists.apache.org/list.html?dev@beam.apache.org)) since we mostly communicate there. While I could add another connector (like the webhook or slack url), email requires a little more config (sender email address and password, recipient email address, email service) which might crowd the options. If we had a generic way of composing this with other actions I could use a send email action or something similar. In general, that kind of composability would be nice :)

**Comment by manuelmhtr** [comment]
Hi @damccorm 
It's a great idea. I saw [this commit](https://github.com/damccorm/pull-request-stats/commit/d7d91cb75a1de21d529683d65df51c6bbc4b9bf5) of yours, which I think solves the problem, but then you reverted the change. Don't you think it could work?

Other ideas:
1. Similar to your commit, I can set 2 outputs: one as a **string** (with the same content as the Github comment) and the other one as **JSON**, which can be parsed and manipulated. Would it work?
2. Another idea for the Beam team might be using Zapier or a similar tool where you can configure a workflow to receive a webhook and then send the results by email or other channels.
3. I configured the [Apache](https://github.com/apache) Github account to use all the "Premium Features" for free. The Slack or Teams connectors could be an alternative in the meanwhile.

**Comment by damccorm** [comment]
Hey, sorry for the slow response, thanks for looking at this!

> I saw [this commit](https://github.com/damccorm/pull-request-stats/commit/d7d91cb75a1de21d529683d65df51c6bbc4b9bf5) of yours, which I think solves the problem, but then you reverted the change. Don't you think it could work?

I didn't go with that change because (a) I wasn't sure if it fit the code style here and (b) it was formatted kinda oddly since it was markdown

> Similar to your commit, I can set 2 outputs: one as a string (with the same content as the Github comment) and the other one as JSON, which can be parsed and manipulated. Would it work?

I think that would be perfect; the JSON bit in particular would be awesome

> I configured the [Apache](https://github.com/apache) Github account to use all the "Premium Features" for free. The Slack or Teams connectors could be an alternative in the meanwhile.

Thank you, that's awesome!

**Comment by damccorm** [comment]
The commit itself might be more or less what we need, I just didn't quite get to testing/validating it in full

**Comment by damccorm** [comment]
Actually, with nodemailer's html option I was able to get this working with just my change; that alone might be enough. I added #76 - let me know what you think!
