### ISSUE TITLE
error: users with special characters?

### ISSUE THREAD

**Issue by RandyMcMillan** [flowwer-dev/pull-request-stats#74]
https://github.com/lightningnetwork/lnd/actions/runs/5545330304/jobs/10124096067?pr=7831

**Comment by manuelmhtr** [comment]
Hi @RandyMcMillan. Sorry, but I didn't catch the problem. Could you explain it?

**Comment by RandyMcMillan** [comment]
the job I was referencing has been purged...

the original PR that prompted the issue:
https://github.com/lightningnetwork/lnd/pull/7831

If memory serves: this had to do with non-ascii characters causing CI failures,
specifically when a user places "emojis" in a folder/file path or name.

**Comment by RandyMcMillan** [comment]
As you can see here:

https://github.com/lightningnetwork/lnd/blob/master/docs/DOCKER.md

people really dont consider this stuff like this when they put this stuff into docs.
