### ISSUE TITLE
Update to node 20

### ISSUE THREAD

**Issue by antonindrawan** [flowwer-dev/pull-request-stats#84]
GitHub actions deprecates node16

For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by manuelmhtr** [comment]
Thanks for your help @antonindrawan, Node v20 is now running on [v2.12.0](https://github.com/flowwer-dev/pull-request-stats/releases/tag/v2.12.0)
