### ISSUE TITLE
Feature: Add an `include` option to filter users based on specified usernames

### ISSUE THREAD

**Issue by y-temp4** [flowwer-dev/pull-request-stats#99]
I propose adding an include option that works in the opposite way of the exclude option, allowing only specific users to be displayed in the results.

**Comment by manuelmhtr** [comment]
Hello @y-temp4 it's a good idea. I'll include it in a future release.

**Comment by y-temp4** [comment]
@manuelmhtr Thank you! I’m looking forward to seeing it in the future release 😊

**Comment by manuelmhtr** [comment]
@y-temp4 the option `include` it's now available in [v3.2.0](https://github.com/flowwer-dev/pull-request-stats/releases/tag/v3.2.0)

**Comment by y-temp4** [comment]
@manuelmhtr Thank you!
